Real-Dev-Squad/todo-backend

.dockerignore
.github/workflows/deploy.yml
README.Docker.md
production.Dockerfile
requirements.txt

Date: 16-May-2025
Developer Name: @prakashchoudhary07 
- Closes #23 
- Closes #27 
Add deploy-to-ec2.yml file for github actions for deploying todo backend. Create a new production.Docker file for deployment, Added "gunicorn" package for running the server
<details>
</details>
<details>
</details>

Feat: deployment actions for running the service

---

production.Dockerfile

Date: 28-05-25
Developer Name: @prakashchoudhary07 
---
<details>
</details>
<details>

fix: deployment issues

---

.github/workflows/test.yml
requirements.txt
todo/tests/integration/base_mongo_test.py
todo/tests/integration/test_task_detail_api.py
todo/tests/integration/test_tasks_delete.py
todo/tests/testcontainers/mongo_container.py
todo/tests/testcontainers/shared_mongo.py
todo_project/db/config.py

Date: 8 June, 2025
---
- Closes #68 
- Integrated MongoDB Testcontainer to spin up a real MongoDB instance during integration tests, replacing mocks and improving test reliability and coverage.
- Refactored two integration test files to use the real MongoDB instance via Testcontainers instead of mocking the database layer.
<details>
https://github.com/user-attachments/assets/d58ebf71-3706-4fe4-b0d6-70f1c5e84687
</details>
<details>
</details>
Integrate MongoDB Testcontainer for integration testing and refactor the test cases to utilize a real MongoDB instance instead of mocked services.
These changes improve the reliability of the integration tests by using a real MongoDB instance, ensuring more …

feat(test): integrate MongoDB Testcontainer and refactor integration tests to use real DB

---

requirements.txt
todo/views/auth.py
todo/views/health.py
todo/views/task.py
todo_project/settings/base.py
todo_project/urls.py

Add swagger support using `drf-spectacular` to provide OpenAPI documentation for the API, including annotated endpoints for the authentication, task, and health views, alongside configuring and exposing Swagger and Redoc UI endpoints.
These changes are being made to enhance the API's usability by providing developers with a self-documented interface through Swagger and Redoc, which facilitates easier understanding and interaction with the API endpoints. Additionally, implementing this documentation standard aligns with best practices for API development, allowing for better support, maintenance, and scaling of the application.

swagger support

---

todo/views/auth.py
todo/views/task.py
todo_project/urls.py

Date: 
---
<details>
</details>
<details>
</details>
Add Swagger UI at the base path in the URL configuration.
These changes are being made to provide a user-friendly interface for API documentation at the application's root URL, enhancing the ease of access for developers to explore and interact with the API endpoints. This approach makes it more convenient for users to locate the documentation without needing to navigate additional paths.

feat: Add Swagger UI at base path in URL configuration

---

todo_project/settings/production.py
todo_project/settings/staging.py
todo_project/urls.py

Date: 
---
<details>
</details>
<details>
</details>
Update Swagger UI settings in production and staging configurations to use specific URL paths, and remove the Swagger UI from the base URL path in `todo_project/urls.py`.
These updates ensure that the Swagger UI is correctly configured with distinct URL paths for the production and staging environments, improving organization and access to API documentation. Removing Swagger UI from the base path helps streamline URL routing and reduces potential conflicts with other endpoints.

feat: Update Swagger UI settings for production and staging environments

---

.github/workflows/deploy.yml

Date: 
---
<details>
</details>
<details>
</details>
Correct the formatting of environment variable assignments in the deployment workflow to remove unnecessary spaces.
The additional spaces after the assignment operator were causing misinterpretation of environment variables, potentially leading to build and deployment issues. Removing the spaces ensures that environment variables are correctly assigned and passed to the deployment process, resolving related errors.

fix: Correct formatting of environment variable assignments in deploy workflow

---

.github/workflows/deploy.yml
production.Dockerfile

- **fix: Correct formatting of environment variable assignments in deploy workflow**
- **fix: Update environment variable handling in Docker configuration for deployment**
Date: 
---
<details>
</details>
<details>
</details>
Add environment variable keys to the Docker build process and replace hardcoded environment value with an argument in the Dockerfile.
These changes allow dynamic assignment of environment variables during the Docker build process, increasing flexibility and adapting the Dockerfile to accommodate different environments. This approach enhances the CI/CD workflow by utilizing GitHub Actions environment variables and build arguments, aligning the build process with specific deployment …

fix add env keys to docker

---

production.Dockerfile

Date: 
---
<details>
</details>
<details>
</details>
Set the `DJANGO_SETTINGS_MODULE` environment variable in the Dockerfile for different environments.
This change ensures that the correct Django settings are used based on the specified environment during the Docker build process, facilitating streamlined deployment and configuration management. By dynamically setting this environment variable, the configuration is more flexible and adaptable to different deployment scenarios.

feat: Set Django settings module in Dockerfile

---

.env.example
todo/tests/integration/base_mongo_test.py
todo_project/settings/base.py
todo_project/settings/staging.py

Date: 10-Jul-2025
Developer Name: @VaibhavSingh8 
---
<details>
</details>
<details>
</details>
Refactor variable names related to cookies and RSA keys used in authentication settings, as well as update default URLs for the frontend and RDS backend in the codebase.
These changes aim to streamline environment variable names for consistency across different environments and improve the clarity of settings configurations. The updates to the default URLs better align with intended environments and purpose, specifically catering to the staging environment requirements. The changes enhance maintainability and readability of the code, ensuring that the environment settings are clear and easy to manage.
> Is this description stale? …

refactor: cookie, rsa and other variable names used in auth

---

todo/repositories/task_repository.py
todo/services/task_service.py
todo/tests/integration/test_task_sorting_integration.py
todo/tests/integration/test_tasks_pagination.py
todo/tests/unit/repositories/test_task_repository.py
todo/tests/unit/services/test_task_service.py
todo/tests/unit/views/test_task.py
todo/views/task.py

Date: `July 11, 2025`
Developer Name: @Achintya-Chatterjee 
---
- Fix security vulnerability where GET /v1/tasks returned all users' tasks
- Implement user-specific task filtering to show only authenticated user's tasks
- Add user_id parameter throughout repository, service, and view layers
<details>
https://github.com/user-attachments/assets/8c3b5f7d-60c8-4163-8141-be1498f68772
</details>
<details>
</details>
Implement user authentication and task filtering for the `GET /v1/tasks` endpoint.
These changes are made to ensure that users only retrieve tasks that they are authorized to see, either tasks they created or tasks assigned to them. This enhances data security and privacy by restricting access to relevant entities. The …

fix: implement user authentication and task filtering for GET /v1/tasks

---

todo/tests/unit/views/test_task.py
todo/utils/invite_code_utils.py
todo/views/label.py
todo/views/task.py

Date: `July 12, 2025`
Developer Name: @Achintya-Chatterjee 
---
- 
- Fix inconsistent null field handling across task endpoints
- Standardize response serialization to always include null fields
- Ensure CREATE and GET endpoints return consistent data structures
- Remove exclude_none=True from Pydantic model serialization
- Improve frontend compatibility with predictable field presence
<details>
</details>
<details>
</details>
Remove `exclude_none=True` argument from the `model_dump` method calls to make null field handling consistent across task endpoint responses.
The `exclude_none=True` argument caused inconsistencies in handling null fields across task endpoints, leading to unexpected data omissions in API responses. …

fix: inconsistent null field handling across task endpoints

---

todo/management/__init__.py
todo/management/commands/__init__.py
todo/management/commands/migrate_labels.py
todo/services/label_service.py
todo_project/db/init.py
todo_project/db/migrations.py

Date: `July 12, 2025`
Developer Name: @Achintya-Chatterjee 
---
- 
- Add migration framework for database schema changes
- Implement fixed labels migration with 8 predefined labels:
* Feature, Bug, Refactoring/Optimization, API
* UI/UX, Testing, Documentation, Review
- Create comprehensive migration system with proper error handling
- Add Django management command for manual migration execution
- Integrate migrations into database initialization workflow
- Ensure idempotent operations for safe re-execution
- Add validation using LabelModel for data integrity
- Support Docker MongoDB deployment with proper transaction handling
<details>
</details>
<details>
</details>
Implement a fixed label system by adding a new migration to …

feat(labels): implement fixed label system with database migration

---

.env.example
.github/workflows/deploy.yml
todo_project/settings/base.py

Date: 
---
<details>
</details>
<details>
</details>
Update the environment configuration to use `SWAGGER_UI_PATH` instead of `SWAGGER_UI_URL` for the Swagger UI path.
This change aligns the environment variable name with the expected functionality by clarifying that the variable represents a path, not a complete URL, thus enhancing code readability and configuration consistency. The update addresses potential confusion and misconfiguration in deployment environments where paths are specified.

feat: Update environment configuration for Swagger UI path

---

todo/constants/messages.py
todo/dto/watchlist_dto.py
todo/repositories/watchlist_repository.py
todo/serializers/update_watchlist_serializer.py
todo/services/watchlist_service.py
todo/urls.py
todo/views/watchlist.py

Date: 14 July 2025
---
- Added the update api for the watchlist using this we can modify the isActive field
<details>
</details>
<details>
</details>

feat: implement update functionality for watchlist tasks

---

todo/dto/responses/get_user_teams_response.py
todo/repositories/team_repository.py
todo/services/team_service.py
todo/tests/unit/services/test_team_service.py
todo/tests/unit/views/test_team.py
todo/views/team.py

Date: 14 July 2025
Developer Name: @yesyash 
---
- Added the get teams api
<details>
</details>
<details>
</details>
Add an API endpoint to retrieve a list of teams associated with a specific user.
The changes are introduced to enable users to view all teams they are associated with, addressing a user accessibility requirement. A new `GetUserTeamsResponse` model is created to format the API response, and new logic is added in `TeamService` and `TeamListView` to handle team retrieval requests efficiently. This approach ensures standardized handling of team data and seamless integration with existing team-related functionalities, covering both unit and view-level tests to ensure full feature coverage.
> Is this description …

feat: adds api to get list of teams for a user

---

todo/services/user_service.py
todo/views/team.py

Refactor the user retrieval logic in the `team.py` view to improve code readability and maintainability.
The existing code for appending `UserDTO` instances to a list was not optimally formatted for readability, with formatting adjustments made to enhance clarity for developers. Additionally, a minor code style change was introduced in the import section of the `team.py` view to maintain a consistent coding style and readability.

feat: refactor user retrieval in team detail view to improve readability

---

todo/tests/integration/base_mongo_test.py
todo/tests/integration/test_task_defer_api.py
todo/tests/integration/test_task_update_api.py
todo/tests/integration/test_tasks_delete.py
todo/tests/unit/repositories/test_task_repository.py
todo/tests/unit/serializers/test_create_task_serializer.py
todo/tests/unit/serializers/test_update_task_serializer.py
todo/tests/unit/services/test_task_service.py

Date: 14 July 2025
---
- #86 
- Added test for the unauthorized user on task creation, task update , task delete
<details>
</details>
<details>
</details>
Add integration tests to verify unauthorized access behavior for defer, update, and delete task operations, and extend serializers to reject invalid assignee input.
These changes are implemented to ensure robustness and correct application behavior in response to unauthorized task operation attempts and to enforce data validation by rejecting invalid assignee inputs during task creation and updates. Adding these tests strengthens security by verifying that only authorized users can perform certain actions on tasks, and improves data integrity …

feat: add unauthorized task operation tests for defer, update, and delete actions

---

todo/management/commands/migrate_add_creator_to_teams.py
todo/repositories/team_repository.py
todo/tests/unit/repositories/test_user_repository.py
todo/views/watchlist.py

Add a Django management command to backfill creator as an active member for each existing team, implement the `get_user_infos_by_team_id` method in `TeamRepository`, and enhance the watchlist API documentation with detailed schema and parameter descriptions.
The changes address the need to ensure team data consistency by retrospectively adding creators to teams where missing and enhance the team's user data management capabilities. Additionally, these improvements in API documentation promote a clearer understanding of watchlist endpoints, facilitating integration and maintenance efforts.

Team member fix

---

schema.yaml
todo/dto/task_dto.py
todo/services/task_service.py
todo/tests/unit/views/test_task.py
todo/tests/unit/views/test_watchlist_check.py
todo/views/task.py
todo/views/watchlist.py

Enhance the watchlist functionality in the Todo API to accurately reflect task watch list statuses as `true`, `false`, or `null`, and update API documentation to enhance clarity and accuracy.
The change is aimed at improving the representation of task states in the watchlist, where `null` is used to signify not being in a watchlist, thus enhancing task filtering precision. Furthermore, it ensures the API documentation reflects these changes and provides a consistent understanding of task watchlist statuses for developers interfacing with the system.

Enhance watchlist functionality and API documentation

---

todo/repositories/assignee_task_details_repository.py
todo/repositories/task_repository.py
todo/services/task_assignment_service.py

Enhance logging and error handling in task repositories and modify the task assignment service to insert into `assignee_task_details` for team assignments.
These changes improve the system's reliability and debuggability by adding logging statements to trace the execution flow and better handle errors in `assignee_task_details_repository.py` and `task_repository.py`. The modification in `task_assignment_service.py` ensures that team assignments are properly recorded in the `assignee_task_details` collection, addressing data consistency needs for team-based tasks.

feat: enhance logging and error handling in task repositories

---

schema.yaml
todo/dto/update_team_dto.py
todo/repositories/team_repository.py
todo/repositories/user_repository.py
todo/serializers/update_team_serializer.py
todo/services/team_service.py
todo/views/team.py

Date: 17/07/2025
Developer Name: @lakshayman 
---
#149 
Patch API to update a team's basic details and team members
Payload:
{
name: "",
description: "",
member_ids: [...],
poc_id: ""
}
<details>
https://github.com/user-attachments/assets/928d353c-7e52-4250-bcbb-795ce1bd2fd3
</details>
Add functionality to update team details and manage team members via a new PATCH endpoint.
These changes enhance the API to allow partial updates to a team's information, such as name, description, point of contact, and member list, thereby offering more flexibility in team management. This update supports dynamic team member modifications, replacing existing members with a new list when provided, or retaining the current members otherwise.
> Is this description stale? Ask me …

feat: update team basic details and members

---

schema.yaml
todo/dto/add_team_member_dto.py
todo/serializers/add_team_member_serializer.py
todo/services/team_service.py
todo/urls.py
todo/views/team.py

Add an endpoint and implement the logic for adding new members to a team, including the necessary request handlers, serializers, and services to facilitate this function.
There was a need for existing team members to invite additional users to join their team, enhancing collaboration and team management capabilities within the application. This implementation restricts the ability to add members only to current team members to maintain proper team access control. This approach ensures new members are valid users and not already part of the team, mitigating potential errors or duplication.

feat: add endpoint and logic for adding team members

---

todo/serializers/create_task_assignment_serializer.py
todo/urls.py
todo/views/task.py

Add an endpoint to assign tasks to users in the todo application, including the necessary serializer, URL routing, and view logic.
To enhance the todo application by allowing tasks to be assigned to specific users, which is crucial for managing task responsibilities within a team or organization. This feature is implemented to support the existing task management system while ensuring proper validation and error handling.

feat: add endpoint to assign tasks to users

---

todo/models/user.py

Date: 
---
<details>
</details>
<details>
</details>
Make the `picture` field in the `UserModel` optional by allowing it to be `None`.
This change is being made to accommodate users who may not have a profile picture, thus improving the flexibility of the user model. By defaulting the `picture` field to `None`, it ensures that creating user entries without a picture does not cause errors or enforce unnecessary data constraints.

fix: allow picture field to be optional in UserModel

---

todo/tests/integration/test_user_profile_api.py
todo/tests/unit/models/test_user.py
todo/tests/unit/views/test_auth.py
todo/views/user.py

Date: 18 July 2025
Developer Name: Prakash
---
- N/A
<details>
</details>
<details>
</details>
Update the response message to "Users fetched successfully" and remove the check for empty users in the `UsersView`.
Removing the empty users check simplifies the code by eliminating an unnecessary 204 No Content response case, as fetching users can imply an empty list rather than a particular message. The response message update provides a more accurate representation of the operation performed, aligning semantics with actual processing.

fix: update response message and remove empty users check in UsersView

---

todo/services/task_service.py

Refactor the label validation process in the `TaskService` to remove redundant logic and streamline ID processing for label validation during task creation.
The original code contained unnecessary validation steps when processing labels, resulting in redundant validations and string conversions. This refactoring simplifies the process by directly converting label IDs to `PyObjectId` and performing validation within the `create_task` method, which ensures consistency and efficiency in label handling.

refactor: streamline label validation in TaskService

---

todo/dto/responses/create_task_assignment_response.py
todo/dto/task_assignment_dto.py
todo/repositories/assignee_task_details_repository.py
todo/services/task_assignment_service.py
todo/views/task.py

Date: 
---
<details>
</details>
<details>
</details>
Refactor task assignment handling to use `relation_type` instead of `user_type` and update relevant class, module imports, and repository methods accordingly.
The refactoring aims to improve semantic clarity and better align the terminology with the application domain by replacing `user_type` with `relation_type`. Additionally, an update method was added to reuse existing assignments when possible, improving performance and consistency.

refactor: update task assignment handling to use relation_type instead of user_type

---

todo/repositories/task_repository.py

Simplify task query filters in `TaskRepository` by removing redundant conditions related to user-created tasks.
The original query included a condition to filter by tasks created by the user, which is no longer necessary due to logic changes that ensure the task lists only contain assigned tasks. This refactoring improves the code's readability and performance by eliminating unnecessary filtering.

refactor: simplify task query filters in TaskRepository

---

todo/services/task_service.py
todo/tests/unit/services/test_task_service.py
todo/tests/unit/views/test_task.py
todo/urls.py
todo/views/task.py

Add a new feature to update task details along with assignee management and implement respective unit tests, view logic, and API endpoint.
This change provides functionality to modify task attributes and manage task assignees in a single operation, which enhances usability and efficiency. The update includes a new method `update_task_with_assignee` in the TaskService, corresponding tests for various scenarios, and addition of a `TaskUpdateView` to handle HTTP requests, ensuring comprehensive support for updating tasks and assignees concurrently.

feat: add task update functionality with assignee management

---

todo/repositories/task_repository.py
todo/repositories/team_repository.py
todo/services/task_service.py

Refactor the task assignment logic to switch from `AssigneeTaskDetailsRepository` to `TaskAssignmentRepository` for fetching team assignments, and enhance team member verification by adding a method to check if a user is a team member instead of just a SPOC (Single Point of Contact).
The change to the repository improves code clarity and consistency across the system by using a dedicated `TaskAssignmentRepository`. The enhancement to team member checks makes task access more inclusive by allowing any team member, not just the SPOC, to view team tasks, thus aligning with potential team dynamics and improving usability.

refactor: update task assignment logic and enhance team member checks

---

todo/repositories/task_assignment_repository.py

Date: July 19 2025
Developer Name: Yash Raj
Refactor the task assignment logic to remove ObjectId conversions for `executor_id` and `user_id` and add a new field `user_type` with a default value of "user".
The conversion to `ObjectId` was unnecessary for the fields `executor_id` and `user_id`, as these are already expected to be strings, simplifying the code and reducing potential runtime errors. Adding a `user_type` field enhances the schema with more descriptive data about the user without impacting existing functionality.

refactor: update task assignment logic to remove ObjectId conversion

---

debug_assignee.py
test_assignee_with_data.py
todo/dto/watchlist_dto.py
todo/repositories/watchlist_repository.py
todo/services/watchlist_service.py
todo/tests/unit/services/test_watchlist_service.py
todo/views/watchlist.py

Add assignee details to watchlist tasks by incorporating assignee lookup in the task data retrieval process, enhancing the watchlist endpoint to reflect task ownership, and including unit tests to validate these functionalities.
These changes are implemented to solve the issue of having null assignee details in watchlisted tasks by accurately fetching and displaying the assignee information (whether a user or a team) responsible for tasks. This improvement aids in clearer task management and accountability within the watchlist feature.

feat: add assignee details to watchlist tasks

---

todo/dto/watchlist_dto.py
todo/repositories/watchlist_repository.py
todo/services/watchlist_service.py

Date: 5 Aug 2025
---
- We were not sending the deferred Details in the watch list task response 
This PR implements proper deferred task status handling in the watchlist functionality, ensuring that deferred tasks show the correct status and include all necessary deferred details in API responses.
<details>
</details>
<details>
</details>
Add the `deferredDetails` attribute to the `WatchlistDTO` class and update related repository and service logic to handle deferred task status.
These changes accommodate tasks that have been deferred by incorporating `DeferredDetailsModel` into `WatchlistDTO`, ensuring tasks with a deferred time in the future are correctly marked with a status of `DEFERRED`. …

feat: add deferred details to watchlist DTO

---

todo/dto/watchlist_dto.py
todo/repositories/watchlist_repository.py
todo/tests/unit/services/test_watchlist_service.py

Date: 
---
<details>
</details>
<details>
</details>
Replace the `createdBy` type from `str` to `UserDTO` in the `WatchlistDTO` class and update related repository methods to handle the new `UserDTO` structure.
This change improves the representation of the `createdBy` field by storing comprehensive user details instead of just the username or ID, allowing for more detailed user information such as ID, name, added date, and task count within the user DTO. This enhances the system's data integrity and aligns with object-oriented design principles by using Data Transfer Objects (DTOs) for user details.
> Is this description stale? Ask me to generate a new description by commenting …

New wtchlist fix

---

.github/workflows/deploy.yml
.github/workflows/test.yml

Date: 
---
<details>
</details>
<details>
</details>
Add PostgreSQL environment variables to the deployment and testing workflows.
These changes are introduced to enable configuring PostgreSQL connection parameters and dual-write functionality as part of the deployment and testing processes. The inclusion of these variables ensures compatibility with PostgreSQL databases and enhances the workflows with robust data synchronization features, while facilitating streamlined deployment and testing environments.

feat: add PostgreSQL environment variables for deployment and testing workflows

---

todo/services/team_service.py

Date: 25-8-25
Developer Name:  @vinit717 
---
- closes #256
Fix the role assignment in Teams 
Team Creator: Owner, Admin, Member
Team POC: Member
Team Member: Member
<details>
</details>
<details>
</details>
Update the user role assignment during team creation to utilize the `RoleName` constants for consistent role naming and ensure correct role assignment.
The change standardizes the role naming by using `RoleName` constants, reducing hard-coded strings and potential errors due to typos. It also optimizes role assignment logic by ensuring that users have all relevant roles uniformly applied, enhancing maintainability and clarity.
> Is this description stale? Ask me to generate a new description by commenting …

fix: update user role assignment during team creation

---

todo/middlewares/team_access_middleware.py
todo/tests/unit/middlewares/test_team_access_middleware.py
todo/views/task.py
todo/views/team.py
todo_project/settings/base.py

Date: 26 Sep 2025
---
- #274 
- #275 
- Added a middleware for the team info api so only team members can view the team related informations
<details>
<summary>Staging Proof</summary>
https://github.com/user-attachments/assets/18d781d4-e528-40f8-9da5-8c488e89dc3d
</details>
> [!NOTE]
> I'm currently writing a description for your pull request. I should be done shortly (<1 minute). Please don't edit the description field until I'm finished, or we may overwrite each other. If I find nothing to write about, I'll delete this message.

Dev to Main Sync
